/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CartButon: typeof import('./components/CartButon.vue')['default']
    CartButton: typeof import('./components/CartButton.vue')['default']
    FilterComponent: typeof import('./components/FilterComponent.vue')['default']
    FooterComponent: typeof import('./components/FooterComponent.vue')['default']
    NavbarComponent: typeof import('./components/NavbarComponent.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
